version: '2.1'
services:
  app:
    build:
      context: ./app
  gateway:
    build:
      context: ./gateway
    links:
      - "app:app"
    environment:
      - APP_HOST=app
      - APP_PORT=3000
    ports:
      - "80:80"
